#Whether to save the game when the server pauses, usually fine without saving.
save-game: false

#How many ticks to step after the server has been paused. After 1 tick the server will usually unload chunks and save them.
step-ticks: 1

#Whether to let clients let the server know they are in the pause menu
enable-mod-companion: true

#Whether to freeze players in place that are on the pause menu while the server is frozen, can cause jittering in some cases
freeze-pause-menu-players: true
