# The delay before the server is frozen in seconds
# Paper has delay-chunk-unloads-by set to 10s by default.
#If you want the server to freeze instantly without issue, in spigot.yml set unload-frozen-chunks to true and set this to 0 OR in paper-world-defaults.yml set delay-chunk-unloads-by to zero & this to 0
freeze-delay: 10